create table course (university_id integer not null, description varchar(255), name varchar(255) not null, rating float, degree_id integer, primary key (university_id)) engine=InnoDB;
create table coursecrn (id integer not null auto_increment, crn_number varchar(255), primary key (id)) engine=InnoDB;
create table degree (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table department (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table instructor (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table level (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table major (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table review (id integer not null auto_increment, is_anonymous bit, content varchar(255), created_at datetime(6) not null, delivery integer, rating float, workload integer, course_id integer, instructor_id integer, university_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table university (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, concentration varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), phone varchar(255), degree_fid integer, major_fid integer, university_fid integer, primary key (id)) engine=InnoDB;
alter table degree add constraint UK_by27bbt64p1ria17hy3khpyft unique (name);
alter table level add constraint UK_lrjnw0jty1fs19q56u0us8d0n unique (name);
alter table major add constraint UK_oi0ctjbjvktdcfxws9w2exiwb unique (name);
alter table university add constraint UK_ru212k5vib3yvu360fuy3h1g5 unique (name);
alter table user add constraint user_email_unique unique (email);
create table course_coursecrns (course_university_id integer not null, coursecrns_id integer not null, primary key (course_university_id, coursecrns_id)) engine=InnoDB;
create table course_instructor (courses_university_id integer not null, instructor_id integer not null, primary key (courses_university_id, instructor_id)) engine=InnoDB;
create table user_course (user_id integer not null, course_university_id integer not null, primary key (user_id, course_university_id)) engine=InnoDB;
create table user_interested_course (user_id integer not null, interested_course_university_id integer not null, primary key (user_id, interested_course_university_id)) engine=InnoDB;
alter table course_coursecrns add constraint UK_sg5l6bj5k4pbeule0v9hi7ahd unique (coursecrns_id);
alter table user_course add constraint UK_ojhtxuq944ptfxntlhrxvcshw unique (course_university_id);
alter table user_interested_course add constraint UK_7g14fn7qjihowhstipo6iy3vd unique (interested_course_university_id);
alter table course add constraint FKdgomx5qg5fvg9cgyh0sdh0vwo foreign key (degree_id) references degree (id);
alter table course add constraint FK4ag2rc4adjiesa1d0lcvnnq82 foreign key (university_id) references university (id);
alter table department add constraint FKh2ap9lv99txektaou64wpx8b2 foreign key (university_id) references university (id);
alter table level add constraint FKkvg8900rbtqtvud24vcsnw6rw foreign key (university_id) references university (id);
alter table review add constraint FKprox8elgnr8u5wrq1983degk foreign key (course_id) references course (university_id);
alter table review add constraint FKd3gy0ma4syq3tkgqyje0nbhb2 foreign key (instructor_id) references instructor (id);
alter table review add constraint FKn3q1vv5fmlyv3ouelg9ta0unb foreign key (university_id) references university (id);
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user (id);
alter table user add constraint FKnqnxmrttbx4tqiv2qkcv1ajcx foreign key (degree_fid) references degree (id);
alter table user add constraint FKfydmmlqn19qnpytrvob21vv4d foreign key (major_fid) references major (id);
alter table user add constraint FK2e0fnf9jmfw0jmwf9m0hihdst foreign key (university_fid) references university (id);
alter table course_coursecrns add constraint FK503m64orid5mj0ivll6oi9l99 foreign key (coursecrns_id) references coursecrn (id);
alter table course_coursecrns add constraint FKjnmg2hil9djxoyml1udh9w9f foreign key (course_university_id) references course (university_id);
alter table course_instructor add constraint FKltori8qni3ivrlovca4gd9yw3 foreign key (instructor_id) references instructor (id);
alter table course_instructor add constraint FK4yrginwid5ipfrsjcwbgddcmm foreign key (courses_university_id) references course (university_id);
alter table user_course add constraint FK4xq18kasyvpo8xmpnpfcr754m foreign key (course_university_id) references course (university_id);
alter table user_course add constraint FKpv8tt3252hb6kyej8p7e7pokl foreign key (user_id) references user (id);
alter table user_interested_course add constraint FKcjdnskifislkh57b59bfquop2 foreign key (interested_course_university_id) references course (university_id);
alter table user_interested_course add constraint FKtlxbvteqs80kpgnwhed1w0vir foreign key (user_id) references user (id);
create table course (university_id integer not null, description varchar(255), name varchar(255) not null, rating float, degree_id integer, primary key (university_id)) engine=InnoDB;
create table coursecrn (id integer not null auto_increment, crn_number varchar(255), primary key (id)) engine=InnoDB;
create table degree (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table department (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table instructor (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table level (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table major (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table review (id integer not null auto_increment, is_anonymous bit, content varchar(255), created_at datetime(6) not null, delivery integer, rating float, workload integer, course_id integer, instructor_id integer, university_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table university (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, concentration varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), phone varchar(255), degree_fid integer, major_fid integer, university_fid integer, primary key (id)) engine=InnoDB;
alter table degree add constraint UK_by27bbt64p1ria17hy3khpyft unique (name);
alter table level add constraint UK_lrjnw0jty1fs19q56u0us8d0n unique (name);
alter table major add constraint UK_oi0ctjbjvktdcfxws9w2exiwb unique (name);
alter table university add constraint UK_ru212k5vib3yvu360fuy3h1g5 unique (name);
alter table user add constraint user_email_unique unique (email);
create table course_coursecrns (course_university_id integer not null, coursecrns_id integer not null, primary key (course_university_id, coursecrns_id)) engine=InnoDB;
create table course_instructor (courses_university_id integer not null, instructor_id integer not null, primary key (courses_university_id, instructor_id)) engine=InnoDB;
create table user_course (user_id integer not null, course_university_id integer not null, primary key (user_id, course_university_id)) engine=InnoDB;
create table user_interested_course (user_id integer not null, interested_course_university_id integer not null, primary key (user_id, interested_course_university_id)) engine=InnoDB;
alter table course_coursecrns add constraint UK_sg5l6bj5k4pbeule0v9hi7ahd unique (coursecrns_id);
alter table user_course add constraint UK_ojhtxuq944ptfxntlhrxvcshw unique (course_university_id);
alter table user_interested_course add constraint UK_7g14fn7qjihowhstipo6iy3vd unique (interested_course_university_id);
alter table course add constraint FKdgomx5qg5fvg9cgyh0sdh0vwo foreign key (degree_id) references degree (id);
alter table course add constraint FK4ag2rc4adjiesa1d0lcvnnq82 foreign key (university_id) references university (id);
alter table department add constraint FKh2ap9lv99txektaou64wpx8b2 foreign key (university_id) references university (id);
alter table level add constraint FKkvg8900rbtqtvud24vcsnw6rw foreign key (university_id) references university (id);
alter table review add constraint FKprox8elgnr8u5wrq1983degk foreign key (course_id) references course (university_id);
alter table review add constraint FKd3gy0ma4syq3tkgqyje0nbhb2 foreign key (instructor_id) references instructor (id);
alter table review add constraint FKn3q1vv5fmlyv3ouelg9ta0unb foreign key (university_id) references university (id);
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user (id);
alter table user add constraint FKnqnxmrttbx4tqiv2qkcv1ajcx foreign key (degree_fid) references degree (id);
alter table user add constraint FKfydmmlqn19qnpytrvob21vv4d foreign key (major_fid) references major (id);
alter table user add constraint FK2e0fnf9jmfw0jmwf9m0hihdst foreign key (university_fid) references university (id);
alter table course_coursecrns add constraint FK503m64orid5mj0ivll6oi9l99 foreign key (coursecrns_id) references coursecrn (id);
alter table course_coursecrns add constraint FKjnmg2hil9djxoyml1udh9w9f foreign key (course_university_id) references course (university_id);
alter table course_instructor add constraint FKltori8qni3ivrlovca4gd9yw3 foreign key (instructor_id) references instructor (id);
alter table course_instructor add constraint FK4yrginwid5ipfrsjcwbgddcmm foreign key (courses_university_id) references course (university_id);
alter table user_course add constraint FK4xq18kasyvpo8xmpnpfcr754m foreign key (course_university_id) references course (university_id);
alter table user_course add constraint FKpv8tt3252hb6kyej8p7e7pokl foreign key (user_id) references user (id);
alter table user_interested_course add constraint FKcjdnskifislkh57b59bfquop2 foreign key (interested_course_university_id) references course (university_id);
alter table user_interested_course add constraint FKtlxbvteqs80kpgnwhed1w0vir foreign key (user_id) references user (id);
create table course (university_id integer not null, description varchar(255), name varchar(255) not null, rating float, degree_id integer, primary key (university_id)) engine=InnoDB;
create table coursecrn (id integer not null auto_increment, crn_number varchar(255), primary key (id)) engine=InnoDB;
create table degree (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table department (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table instructor (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table level (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table major (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table review (id integer not null auto_increment, is_anonymous bit, content varchar(255), created_at datetime(6) not null, delivery integer, rating float, workload integer, course_id integer, instructor_id integer, university_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table university (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, concentration varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), phone varchar(255), degree_fid integer, major_fid integer, university_fid integer, primary key (id)) engine=InnoDB;
alter table degree add constraint UK_by27bbt64p1ria17hy3khpyft unique (name);
alter table level add constraint UK_lrjnw0jty1fs19q56u0us8d0n unique (name);
alter table major add constraint UK_oi0ctjbjvktdcfxws9w2exiwb unique (name);
alter table university add constraint UK_ru212k5vib3yvu360fuy3h1g5 unique (name);
alter table user add constraint user_email_unique unique (email);
create table course_coursecrns (course_university_id integer not null, coursecrns_id integer not null, primary key (course_university_id, coursecrns_id)) engine=InnoDB;
create table course_instructor (courses_university_id integer not null, instructor_id integer not null, primary key (courses_university_id, instructor_id)) engine=InnoDB;
create table user_course (user_id integer not null, course_university_id integer not null, primary key (user_id, course_university_id)) engine=InnoDB;
create table user_interested_course (user_id integer not null, interested_course_university_id integer not null, primary key (user_id, interested_course_university_id)) engine=InnoDB;
alter table course_coursecrns add constraint UK_sg5l6bj5k4pbeule0v9hi7ahd unique (coursecrns_id);
alter table user_course add constraint UK_ojhtxuq944ptfxntlhrxvcshw unique (course_university_id);
alter table user_interested_course add constraint UK_7g14fn7qjihowhstipo6iy3vd unique (interested_course_university_id);
alter table course add constraint FKdgomx5qg5fvg9cgyh0sdh0vwo foreign key (degree_id) references degree (id);
alter table course add constraint FK4ag2rc4adjiesa1d0lcvnnq82 foreign key (university_id) references university (id);
alter table department add constraint FKh2ap9lv99txektaou64wpx8b2 foreign key (university_id) references university (id);
alter table level add constraint FKkvg8900rbtqtvud24vcsnw6rw foreign key (university_id) references university (id);
alter table review add constraint FKprox8elgnr8u5wrq1983degk foreign key (course_id) references course (university_id);
alter table review add constraint FKd3gy0ma4syq3tkgqyje0nbhb2 foreign key (instructor_id) references instructor (id);
alter table review add constraint FKn3q1vv5fmlyv3ouelg9ta0unb foreign key (university_id) references university (id);
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user (id);
alter table user add constraint FKnqnxmrttbx4tqiv2qkcv1ajcx foreign key (degree_fid) references degree (id);
alter table user add constraint FKfydmmlqn19qnpytrvob21vv4d foreign key (major_fid) references major (id);
alter table user add constraint FK2e0fnf9jmfw0jmwf9m0hihdst foreign key (university_fid) references university (id);
alter table course_coursecrns add constraint FK503m64orid5mj0ivll6oi9l99 foreign key (coursecrns_id) references coursecrn (id);
alter table course_coursecrns add constraint FKjnmg2hil9djxoyml1udh9w9f foreign key (course_university_id) references course (university_id);
alter table course_instructor add constraint FKltori8qni3ivrlovca4gd9yw3 foreign key (instructor_id) references instructor (id);
alter table course_instructor add constraint FK4yrginwid5ipfrsjcwbgddcmm foreign key (courses_university_id) references course (university_id);
alter table user_course add constraint FK4xq18kasyvpo8xmpnpfcr754m foreign key (course_university_id) references course (university_id);
alter table user_course add constraint FKpv8tt3252hb6kyej8p7e7pokl foreign key (user_id) references user (id);
alter table user_interested_course add constraint FKcjdnskifislkh57b59bfquop2 foreign key (interested_course_university_id) references course (university_id);
alter table user_interested_course add constraint FKtlxbvteqs80kpgnwhed1w0vir foreign key (user_id) references user (id);
create table course (university_id integer not null, description varchar(255), name varchar(255) not null, rating float, degree_id integer, primary key (university_id)) engine=InnoDB;
create table coursecrn (id integer not null auto_increment, crn_number varchar(255), primary key (id)) engine=InnoDB;
create table degree (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table department (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table instructor (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table level (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table major (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table review (id integer not null auto_increment, is_anonymous bit, content varchar(255), created_at datetime(6) not null, delivery integer, rating float, workload integer, course_id integer, instructor_id integer, university_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table university (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, concentration varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), phone varchar(255), degree_fid integer, major_fid integer, university_fid integer, primary key (id)) engine=InnoDB;
alter table degree add constraint UK_by27bbt64p1ria17hy3khpyft unique (name);
alter table level add constraint UK_lrjnw0jty1fs19q56u0us8d0n unique (name);
alter table major add constraint UK_oi0ctjbjvktdcfxws9w2exiwb unique (name);
alter table university add constraint UK_ru212k5vib3yvu360fuy3h1g5 unique (name);
alter table user add constraint user_email_unique unique (email);
create table course_coursecrns (course_university_id integer not null, coursecrns_id integer not null, primary key (course_university_id, coursecrns_id)) engine=InnoDB;
create table course_instructor (courses_university_id integer not null, instructor_id integer not null, primary key (courses_university_id, instructor_id)) engine=InnoDB;
create table user_course (user_id integer not null, course_university_id integer not null, primary key (user_id, course_university_id)) engine=InnoDB;
create table user_interested_course (user_id integer not null, interested_course_university_id integer not null, primary key (user_id, interested_course_university_id)) engine=InnoDB;
alter table course_coursecrns add constraint UK_sg5l6bj5k4pbeule0v9hi7ahd unique (coursecrns_id);
alter table user_course add constraint UK_ojhtxuq944ptfxntlhrxvcshw unique (course_university_id);
alter table user_interested_course add constraint UK_7g14fn7qjihowhstipo6iy3vd unique (interested_course_university_id);
alter table course add constraint FKdgomx5qg5fvg9cgyh0sdh0vwo foreign key (degree_id) references degree (id);
alter table course add constraint FK4ag2rc4adjiesa1d0lcvnnq82 foreign key (university_id) references university (id);
alter table department add constraint FKh2ap9lv99txektaou64wpx8b2 foreign key (university_id) references university (id);
alter table level add constraint FKkvg8900rbtqtvud24vcsnw6rw foreign key (university_id) references university (id);
alter table review add constraint FKprox8elgnr8u5wrq1983degk foreign key (course_id) references course (university_id);
alter table review add constraint FKd3gy0ma4syq3tkgqyje0nbhb2 foreign key (instructor_id) references instructor (id);
alter table review add constraint FKn3q1vv5fmlyv3ouelg9ta0unb foreign key (university_id) references university (id);
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user (id);
alter table user add constraint FKnqnxmrttbx4tqiv2qkcv1ajcx foreign key (degree_fid) references degree (id);
alter table user add constraint FKfydmmlqn19qnpytrvob21vv4d foreign key (major_fid) references major (id);
alter table user add constraint FK2e0fnf9jmfw0jmwf9m0hihdst foreign key (university_fid) references university (id);
alter table course_coursecrns add constraint FK503m64orid5mj0ivll6oi9l99 foreign key (coursecrns_id) references coursecrn (id);
alter table course_coursecrns add constraint FKjnmg2hil9djxoyml1udh9w9f foreign key (course_university_id) references course (university_id);
alter table course_instructor add constraint FKltori8qni3ivrlovca4gd9yw3 foreign key (instructor_id) references instructor (id);
alter table course_instructor add constraint FK4yrginwid5ipfrsjcwbgddcmm foreign key (courses_university_id) references course (university_id);
alter table user_course add constraint FK4xq18kasyvpo8xmpnpfcr754m foreign key (course_university_id) references course (university_id);
alter table user_course add constraint FKpv8tt3252hb6kyej8p7e7pokl foreign key (user_id) references user (id);
alter table user_interested_course add constraint FKcjdnskifislkh57b59bfquop2 foreign key (interested_course_university_id) references course (university_id);
alter table user_interested_course add constraint FKtlxbvteqs80kpgnwhed1w0vir foreign key (user_id) references user (id);
create table course (id integer not null, description varchar(255), name varchar(255) not null, rating float, degree_id integer, university_id integer, primary key (id)) engine=InnoDB;
create table coursecrn (id integer not null auto_increment, crn_number varchar(255), primary key (id)) engine=InnoDB;
create table degree (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table department (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table instructor (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table level (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table major (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table review (id integer not null auto_increment, is_anonymous bit, content varchar(255), created_at datetime(6) not null, delivery integer, rating float, workload integer, course_id integer, instructor_id integer, university_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table university (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, concentration varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), phone varchar(255), degree_fid integer, major_fid integer, university_fid integer, primary key (id)) engine=InnoDB;
alter table degree add constraint UK_by27bbt64p1ria17hy3khpyft unique (name);
alter table level add constraint UK_lrjnw0jty1fs19q56u0us8d0n unique (name);
alter table major add constraint UK_oi0ctjbjvktdcfxws9w2exiwb unique (name);
alter table university add constraint UK_ru212k5vib3yvu360fuy3h1g5 unique (name);
alter table user add constraint user_email_unique unique (email);
create table course_coursecrns (course_id integer not null, coursecrns_id integer not null, primary key (course_id, coursecrns_id)) engine=InnoDB;
create table course_instructor (courses_id integer not null, instructor_id integer not null, primary key (courses_id, instructor_id)) engine=InnoDB;
create table user_course (user_id integer not null, course_id integer not null, primary key (user_id, course_id)) engine=InnoDB;
create table user_interested_course (user_id integer not null, interested_course_id integer not null, primary key (user_id, interested_course_id)) engine=InnoDB;
alter table course_coursecrns add constraint UK_sg5l6bj5k4pbeule0v9hi7ahd unique (coursecrns_id);
alter table user_course add constraint UK_bca82qqx1k6y56o7mv7sy7pam unique (course_id);
alter table user_interested_course add constraint UK_727ygq5lux6ilf71xgkfnqyh6 unique (interested_course_id);
alter table course add constraint FKdgomx5qg5fvg9cgyh0sdh0vwo foreign key (degree_id) references degree (id);
alter table course add constraint FK4ag2rc4adjiesa1d0lcvnnq82 foreign key (university_id) references university (id);
alter table department add constraint FKh2ap9lv99txektaou64wpx8b2 foreign key (university_id) references university (id);
alter table level add constraint FKkvg8900rbtqtvud24vcsnw6rw foreign key (university_id) references university (id);
alter table review add constraint FKprox8elgnr8u5wrq1983degk foreign key (course_id) references course (id);
alter table review add constraint FKd3gy0ma4syq3tkgqyje0nbhb2 foreign key (instructor_id) references instructor (id);
alter table review add constraint FKn3q1vv5fmlyv3ouelg9ta0unb foreign key (university_id) references university (id);
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user (id);
alter table user add constraint FKnqnxmrttbx4tqiv2qkcv1ajcx foreign key (degree_fid) references degree (id);
alter table user add constraint FKfydmmlqn19qnpytrvob21vv4d foreign key (major_fid) references major (id);
alter table user add constraint FK2e0fnf9jmfw0jmwf9m0hihdst foreign key (university_fid) references university (id);
alter table course_coursecrns add constraint FK503m64orid5mj0ivll6oi9l99 foreign key (coursecrns_id) references coursecrn (id);
alter table course_coursecrns add constraint FKg7swl4871igbcguayn7jlwobd foreign key (course_id) references course (id);
alter table course_instructor add constraint FKltori8qni3ivrlovca4gd9yw3 foreign key (instructor_id) references instructor (id);
alter table course_instructor add constraint FKteff0a8lukm14bmslsh3titiw foreign key (courses_id) references course (id);
alter table user_course add constraint FKka18m18kpimodvy8yg2icu083 foreign key (course_id) references course (id);
alter table user_course add constraint FKpv8tt3252hb6kyej8p7e7pokl foreign key (user_id) references user (id);
alter table user_interested_course add constraint FKexsv0pa0ljgpr17d4ry34xaxc foreign key (interested_course_id) references course (id);
alter table user_interested_course add constraint FKtlxbvteqs80kpgnwhed1w0vir foreign key (user_id) references user (id);
create table course (id integer not null, description varchar(255), name varchar(255) not null, rating float, degree_id integer, university_id integer, primary key (id)) engine=InnoDB;
create table coursecrn (id integer not null auto_increment, crn_number varchar(255), primary key (id)) engine=InnoDB;
create table degree (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table department (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table instructor (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table level (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table major (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table review (id integer not null auto_increment, is_anonymous bit, content varchar(255), created_at datetime(6) not null, delivery integer, rating float, workload integer, course_id integer, instructor_id integer, university_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table university (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, concentration varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), phone varchar(255), degree_fid integer, major_fid integer, university_fid integer, primary key (id)) engine=InnoDB;
alter table degree add constraint UK_by27bbt64p1ria17hy3khpyft unique (name);
alter table level add constraint UK_lrjnw0jty1fs19q56u0us8d0n unique (name);
alter table major add constraint UK_oi0ctjbjvktdcfxws9w2exiwb unique (name);
alter table university add constraint UK_ru212k5vib3yvu360fuy3h1g5 unique (name);
alter table user add constraint user_email_unique unique (email);
create table course_coursecrns (course_id integer not null, coursecrns_id integer not null, primary key (course_id, coursecrns_id)) engine=InnoDB;
create table course_instructor (courses_id integer not null, instructor_id integer not null, primary key (courses_id, instructor_id)) engine=InnoDB;
create table user_course (user_id integer not null, course_id integer not null, primary key (user_id, course_id)) engine=InnoDB;
create table user_interested_course (user_id integer not null, interested_course_id integer not null, primary key (user_id, interested_course_id)) engine=InnoDB;
alter table course_coursecrns add constraint UK_sg5l6bj5k4pbeule0v9hi7ahd unique (coursecrns_id);
alter table user_course add constraint UK_bca82qqx1k6y56o7mv7sy7pam unique (course_id);
alter table user_interested_course add constraint UK_727ygq5lux6ilf71xgkfnqyh6 unique (interested_course_id);
alter table course add constraint FKdgomx5qg5fvg9cgyh0sdh0vwo foreign key (degree_id) references degree (id);
alter table course add constraint FK4ag2rc4adjiesa1d0lcvnnq82 foreign key (university_id) references university (id);
alter table department add constraint FKh2ap9lv99txektaou64wpx8b2 foreign key (university_id) references university (id);
alter table level add constraint FKkvg8900rbtqtvud24vcsnw6rw foreign key (university_id) references university (id);
alter table review add constraint FKprox8elgnr8u5wrq1983degk foreign key (course_id) references course (id);
alter table review add constraint FKd3gy0ma4syq3tkgqyje0nbhb2 foreign key (instructor_id) references instructor (id);
alter table review add constraint FKn3q1vv5fmlyv3ouelg9ta0unb foreign key (university_id) references university (id);
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user (id);
alter table user add constraint FKnqnxmrttbx4tqiv2qkcv1ajcx foreign key (degree_fid) references degree (id);
alter table user add constraint FKfydmmlqn19qnpytrvob21vv4d foreign key (major_fid) references major (id);
alter table user add constraint FK2e0fnf9jmfw0jmwf9m0hihdst foreign key (university_fid) references university (id);
alter table course_coursecrns add constraint FK503m64orid5mj0ivll6oi9l99 foreign key (coursecrns_id) references coursecrn (id);
alter table course_coursecrns add constraint FKg7swl4871igbcguayn7jlwobd foreign key (course_id) references course (id);
alter table course_instructor add constraint FKltori8qni3ivrlovca4gd9yw3 foreign key (instructor_id) references instructor (id);
alter table course_instructor add constraint FKteff0a8lukm14bmslsh3titiw foreign key (courses_id) references course (id);
alter table user_course add constraint FKka18m18kpimodvy8yg2icu083 foreign key (course_id) references course (id);
alter table user_course add constraint FKpv8tt3252hb6kyej8p7e7pokl foreign key (user_id) references user (id);
alter table user_interested_course add constraint FKexsv0pa0ljgpr17d4ry34xaxc foreign key (interested_course_id) references course (id);
alter table user_interested_course add constraint FKtlxbvteqs80kpgnwhed1w0vir foreign key (user_id) references user (id);
create table course (id integer not null, description varchar(255), name varchar(255) not null, rating float, degree_id integer, university_id integer, primary key (id)) engine=InnoDB;
create table coursecrn (id integer not null auto_increment, crn_number varchar(255), primary key (id)) engine=InnoDB;
create table degree (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table department (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table instructor (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table level (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table major (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table review (id integer not null auto_increment, is_anonymous bit, content varchar(255), created_at datetime(6) not null, delivery integer, rating float, workload integer, course_id integer, instructor_id integer, university_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table university (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, concentration varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), phone varchar(255), degree_fid integer, major_fid integer, university_fid integer, primary key (id)) engine=InnoDB;
alter table degree add constraint UK_by27bbt64p1ria17hy3khpyft unique (name);
alter table level add constraint UK_lrjnw0jty1fs19q56u0us8d0n unique (name);
alter table major add constraint UK_oi0ctjbjvktdcfxws9w2exiwb unique (name);
alter table university add constraint UK_ru212k5vib3yvu360fuy3h1g5 unique (name);
alter table user add constraint user_email_unique unique (email);
create table course_coursecrns (course_id integer not null, coursecrns_id integer not null, primary key (course_id, coursecrns_id)) engine=InnoDB;
create table course_instructor (courses_id integer not null, instructor_id integer not null, primary key (courses_id, instructor_id)) engine=InnoDB;
create table user_course (user_id integer not null, course_id integer not null, primary key (user_id, course_id)) engine=InnoDB;
create table user_interested_course (user_id integer not null, interested_course_id integer not null, primary key (user_id, interested_course_id)) engine=InnoDB;
alter table course_coursecrns add constraint UK_sg5l6bj5k4pbeule0v9hi7ahd unique (coursecrns_id);
alter table user_course add constraint UK_bca82qqx1k6y56o7mv7sy7pam unique (course_id);
alter table user_interested_course add constraint UK_727ygq5lux6ilf71xgkfnqyh6 unique (interested_course_id);
alter table course add constraint FKdgomx5qg5fvg9cgyh0sdh0vwo foreign key (degree_id) references degree (id);
alter table course add constraint FK4ag2rc4adjiesa1d0lcvnnq82 foreign key (university_id) references university (id);
alter table department add constraint FKh2ap9lv99txektaou64wpx8b2 foreign key (university_id) references university (id);
alter table level add constraint FKkvg8900rbtqtvud24vcsnw6rw foreign key (university_id) references university (id);
alter table review add constraint FKprox8elgnr8u5wrq1983degk foreign key (course_id) references course (id);
alter table review add constraint FKd3gy0ma4syq3tkgqyje0nbhb2 foreign key (instructor_id) references instructor (id);
alter table review add constraint FKn3q1vv5fmlyv3ouelg9ta0unb foreign key (university_id) references university (id);
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user (id);
alter table user add constraint FKnqnxmrttbx4tqiv2qkcv1ajcx foreign key (degree_fid) references degree (id);
alter table user add constraint FKfydmmlqn19qnpytrvob21vv4d foreign key (major_fid) references major (id);
alter table user add constraint FK2e0fnf9jmfw0jmwf9m0hihdst foreign key (university_fid) references university (id);
alter table course_coursecrns add constraint FK503m64orid5mj0ivll6oi9l99 foreign key (coursecrns_id) references coursecrn (id);
alter table course_coursecrns add constraint FKg7swl4871igbcguayn7jlwobd foreign key (course_id) references course (id);
alter table course_instructor add constraint FKltori8qni3ivrlovca4gd9yw3 foreign key (instructor_id) references instructor (id);
alter table course_instructor add constraint FKteff0a8lukm14bmslsh3titiw foreign key (courses_id) references course (id);
alter table user_course add constraint FKka18m18kpimodvy8yg2icu083 foreign key (course_id) references course (id);
alter table user_course add constraint FKpv8tt3252hb6kyej8p7e7pokl foreign key (user_id) references user (id);
alter table user_interested_course add constraint FKexsv0pa0ljgpr17d4ry34xaxc foreign key (interested_course_id) references course (id);
alter table user_interested_course add constraint FKtlxbvteqs80kpgnwhed1w0vir foreign key (user_id) references user (id);
create table course (university_id integer not null, course_num varchar(255), description varchar(255), name varchar(255) not null, rating float, degree_id integer, primary key (university_id)) engine=InnoDB;
create table coursecrn (id integer not null auto_increment, crn_number varchar(255), primary key (id)) engine=InnoDB;
create table degree (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table department (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table instructor (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table level (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table major (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table review (id integer not null auto_increment, is_anonymous bit, content varchar(255), created_at datetime(6) not null, delivery integer, rating float, workload integer, course_id integer, instructor_id integer, university_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table university (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, concentration varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), phone varchar(255), degree_fid integer, major_fid integer, university_fid integer, primary key (id)) engine=InnoDB;
alter table degree add constraint UK_by27bbt64p1ria17hy3khpyft unique (name);
alter table level add constraint UK_lrjnw0jty1fs19q56u0us8d0n unique (name);
alter table major add constraint UK_oi0ctjbjvktdcfxws9w2exiwb unique (name);
alter table university add constraint UK_ru212k5vib3yvu360fuy3h1g5 unique (name);
alter table user add constraint user_email_unique unique (email);
create table course_coursecrns (course_university_id integer not null, coursecrns_id integer not null, primary key (course_university_id, coursecrns_id)) engine=InnoDB;
create table course_instructor (courses_university_id integer not null, instructor_id integer not null, primary key (courses_university_id, instructor_id)) engine=InnoDB;
create table user_course (user_id integer not null, course_university_id integer not null, primary key (user_id, course_university_id)) engine=InnoDB;
create table user_interested_course (user_id integer not null, interested_course_university_id integer not null, primary key (user_id, interested_course_university_id)) engine=InnoDB;
alter table course_coursecrns add constraint UK_sg5l6bj5k4pbeule0v9hi7ahd unique (coursecrns_id);
alter table user_course add constraint UK_ojhtxuq944ptfxntlhrxvcshw unique (course_university_id);
alter table user_interested_course add constraint UK_7g14fn7qjihowhstipo6iy3vd unique (interested_course_university_id);
alter table course add constraint FKdgomx5qg5fvg9cgyh0sdh0vwo foreign key (degree_id) references degree (id);
alter table course add constraint FK4ag2rc4adjiesa1d0lcvnnq82 foreign key (university_id) references university (id);
alter table department add constraint FKh2ap9lv99txektaou64wpx8b2 foreign key (university_id) references university (id);
alter table level add constraint FKkvg8900rbtqtvud24vcsnw6rw foreign key (university_id) references university (id);
alter table review add constraint FKprox8elgnr8u5wrq1983degk foreign key (course_id) references course (university_id);
alter table review add constraint FKd3gy0ma4syq3tkgqyje0nbhb2 foreign key (instructor_id) references instructor (id);
alter table review add constraint FKn3q1vv5fmlyv3ouelg9ta0unb foreign key (university_id) references university (id);
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user (id);
alter table user add constraint FKnqnxmrttbx4tqiv2qkcv1ajcx foreign key (degree_fid) references degree (id);
alter table user add constraint FKfydmmlqn19qnpytrvob21vv4d foreign key (major_fid) references major (id);
alter table user add constraint FK2e0fnf9jmfw0jmwf9m0hihdst foreign key (university_fid) references university (id);
alter table course_coursecrns add constraint FK503m64orid5mj0ivll6oi9l99 foreign key (coursecrns_id) references coursecrn (id);
alter table course_coursecrns add constraint FKjnmg2hil9djxoyml1udh9w9f foreign key (course_university_id) references course (university_id);
alter table course_instructor add constraint FKltori8qni3ivrlovca4gd9yw3 foreign key (instructor_id) references instructor (id);
alter table course_instructor add constraint FK4yrginwid5ipfrsjcwbgddcmm foreign key (courses_university_id) references course (university_id);
alter table user_course add constraint FK4xq18kasyvpo8xmpnpfcr754m foreign key (course_university_id) references course (university_id);
alter table user_course add constraint FKpv8tt3252hb6kyej8p7e7pokl foreign key (user_id) references user (id);
alter table user_interested_course add constraint FKcjdnskifislkh57b59bfquop2 foreign key (interested_course_university_id) references course (university_id);
alter table user_interested_course add constraint FKtlxbvteqs80kpgnwhed1w0vir foreign key (user_id) references user (id);
create table course (university_id integer not null, course_num varchar(255), description varchar(255), name varchar(255) not null, rating float, degree_id integer, primary key (university_id)) engine=InnoDB;
create table coursecrn (id integer not null auto_increment, crn_number varchar(255), primary key (id)) engine=InnoDB;
create table degree (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table department (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table instructor (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table level (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table major (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table review (id integer not null auto_increment, is_anonymous bit, content varchar(255), created_at datetime(6) not null, delivery integer, rating float, workload integer, course_id integer, instructor_id integer, university_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table university (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, concentration varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), phone varchar(255), degree_fid integer, major_fid integer, university_fid integer, primary key (id)) engine=InnoDB;
alter table degree add constraint UK_by27bbt64p1ria17hy3khpyft unique (name);
alter table level add constraint UK_lrjnw0jty1fs19q56u0us8d0n unique (name);
alter table major add constraint UK_oi0ctjbjvktdcfxws9w2exiwb unique (name);
alter table university add constraint UK_ru212k5vib3yvu360fuy3h1g5 unique (name);
alter table user add constraint user_email_unique unique (email);
create table course_coursecrns (course_university_id integer not null, coursecrns_id integer not null, primary key (course_university_id, coursecrns_id)) engine=InnoDB;
create table course_instructor (courses_university_id integer not null, instructor_id integer not null, primary key (courses_university_id, instructor_id)) engine=InnoDB;
create table user_course (user_id integer not null, course_university_id integer not null, primary key (user_id, course_university_id)) engine=InnoDB;
create table user_interested_course (user_id integer not null, interested_course_university_id integer not null, primary key (user_id, interested_course_university_id)) engine=InnoDB;
alter table course_coursecrns add constraint UK_sg5l6bj5k4pbeule0v9hi7ahd unique (coursecrns_id);
alter table user_course add constraint UK_ojhtxuq944ptfxntlhrxvcshw unique (course_university_id);
alter table user_interested_course add constraint UK_7g14fn7qjihowhstipo6iy3vd unique (interested_course_university_id);
alter table course add constraint FKdgomx5qg5fvg9cgyh0sdh0vwo foreign key (degree_id) references degree (id);
alter table course add constraint FK4ag2rc4adjiesa1d0lcvnnq82 foreign key (university_id) references university (id);
alter table department add constraint FKh2ap9lv99txektaou64wpx8b2 foreign key (university_id) references university (id);
alter table level add constraint FKkvg8900rbtqtvud24vcsnw6rw foreign key (university_id) references university (id);
alter table review add constraint FKprox8elgnr8u5wrq1983degk foreign key (course_id) references course (university_id);
alter table review add constraint FKd3gy0ma4syq3tkgqyje0nbhb2 foreign key (instructor_id) references instructor (id);
alter table review add constraint FKn3q1vv5fmlyv3ouelg9ta0unb foreign key (university_id) references university (id);
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user (id);
alter table user add constraint FKnqnxmrttbx4tqiv2qkcv1ajcx foreign key (degree_fid) references degree (id);
alter table user add constraint FKfydmmlqn19qnpytrvob21vv4d foreign key (major_fid) references major (id);
alter table user add constraint FK2e0fnf9jmfw0jmwf9m0hihdst foreign key (university_fid) references university (id);
alter table course_coursecrns add constraint FK503m64orid5mj0ivll6oi9l99 foreign key (coursecrns_id) references coursecrn (id);
alter table course_coursecrns add constraint FKjnmg2hil9djxoyml1udh9w9f foreign key (course_university_id) references course (university_id);
alter table course_instructor add constraint FKltori8qni3ivrlovca4gd9yw3 foreign key (instructor_id) references instructor (id);
alter table course_instructor add constraint FK4yrginwid5ipfrsjcwbgddcmm foreign key (courses_university_id) references course (university_id);
alter table user_course add constraint FK4xq18kasyvpo8xmpnpfcr754m foreign key (course_university_id) references course (university_id);
alter table user_course add constraint FKpv8tt3252hb6kyej8p7e7pokl foreign key (user_id) references user (id);
alter table user_interested_course add constraint FKcjdnskifislkh57b59bfquop2 foreign key (interested_course_university_id) references course (university_id);
alter table user_interested_course add constraint FKtlxbvteqs80kpgnwhed1w0vir foreign key (user_id) references user (id);
create table course (university_id integer not null, course_num varchar(255), description varchar(255), name varchar(255) not null, rating float, degree_id integer, primary key (university_id)) engine=InnoDB;
create table coursecrn (id integer not null auto_increment, crn_number varchar(255), primary key (id)) engine=InnoDB;
create table degree (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table department (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table instructor (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table level (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table major (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table review (id integer not null auto_increment, is_anonymous bit, content varchar(255), created_at datetime(6) not null, delivery integer, rating float, workload integer, course_id integer, instructor_id integer, university_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table university (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, concentration varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), phone varchar(255), degree_fid integer, major_fid integer, university_fid integer, primary key (id)) engine=InnoDB;
alter table degree add constraint UK_by27bbt64p1ria17hy3khpyft unique (name);
alter table level add constraint UK_lrjnw0jty1fs19q56u0us8d0n unique (name);
alter table major add constraint UK_oi0ctjbjvktdcfxws9w2exiwb unique (name);
alter table university add constraint UK_ru212k5vib3yvu360fuy3h1g5 unique (name);
alter table user add constraint user_email_unique unique (email);
create table course_coursecrns (course_university_id integer not null, coursecrns_id integer not null, primary key (course_university_id, coursecrns_id)) engine=InnoDB;
create table course_instructor (courses_university_id integer not null, instructor_id integer not null, primary key (courses_university_id, instructor_id)) engine=InnoDB;
create table user_course (user_id integer not null, course_university_id integer not null, primary key (user_id, course_university_id)) engine=InnoDB;
create table user_interested_course (user_id integer not null, interested_course_university_id integer not null, primary key (user_id, interested_course_university_id)) engine=InnoDB;
alter table course_coursecrns add constraint UK_sg5l6bj5k4pbeule0v9hi7ahd unique (coursecrns_id);
alter table user_course add constraint UK_ojhtxuq944ptfxntlhrxvcshw unique (course_university_id);
alter table user_interested_course add constraint UK_7g14fn7qjihowhstipo6iy3vd unique (interested_course_university_id);
alter table course add constraint FKdgomx5qg5fvg9cgyh0sdh0vwo foreign key (degree_id) references degree (id);
alter table course add constraint FK4ag2rc4adjiesa1d0lcvnnq82 foreign key (university_id) references university (id);
alter table department add constraint FKh2ap9lv99txektaou64wpx8b2 foreign key (university_id) references university (id);
alter table level add constraint FKkvg8900rbtqtvud24vcsnw6rw foreign key (university_id) references university (id);
alter table review add constraint FKprox8elgnr8u5wrq1983degk foreign key (course_id) references course (university_id);
alter table review add constraint FKd3gy0ma4syq3tkgqyje0nbhb2 foreign key (instructor_id) references instructor (id);
alter table review add constraint FKn3q1vv5fmlyv3ouelg9ta0unb foreign key (university_id) references university (id);
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user (id);
alter table user add constraint FKnqnxmrttbx4tqiv2qkcv1ajcx foreign key (degree_fid) references degree (id);
alter table user add constraint FKfydmmlqn19qnpytrvob21vv4d foreign key (major_fid) references major (id);
alter table user add constraint FK2e0fnf9jmfw0jmwf9m0hihdst foreign key (university_fid) references university (id);
alter table course_coursecrns add constraint FK503m64orid5mj0ivll6oi9l99 foreign key (coursecrns_id) references coursecrn (id);
alter table course_coursecrns add constraint FKjnmg2hil9djxoyml1udh9w9f foreign key (course_university_id) references course (university_id);
alter table course_instructor add constraint FKltori8qni3ivrlovca4gd9yw3 foreign key (instructor_id) references instructor (id);
alter table course_instructor add constraint FK4yrginwid5ipfrsjcwbgddcmm foreign key (courses_university_id) references course (university_id);
alter table user_course add constraint FK4xq18kasyvpo8xmpnpfcr754m foreign key (course_university_id) references course (university_id);
alter table user_course add constraint FKpv8tt3252hb6kyej8p7e7pokl foreign key (user_id) references user (id);
alter table user_interested_course add constraint FKcjdnskifislkh57b59bfquop2 foreign key (interested_course_university_id) references course (university_id);
alter table user_interested_course add constraint FKtlxbvteqs80kpgnwhed1w0vir foreign key (user_id) references user (id);
create table course (university_id integer not null, course_num varchar(255), description varchar(255), name varchar(255) not null, rating float, degree_id integer, primary key (university_id)) engine=InnoDB;
create table coursecrn (id integer not null auto_increment, crn_number varchar(255), primary key (id)) engine=InnoDB;
create table degree (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table department (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table instructor (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table level (id integer not null auto_increment, name varchar(255), university_id integer, primary key (id)) engine=InnoDB;
create table major (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table review (id integer not null auto_increment, is_anonymous bit, content varchar(255), created_at datetime(6) not null, delivery integer, rating float, workload integer, course_id integer, instructor_id integer, university_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table university (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, concentration varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), phone varchar(255), degree_fid integer, major_fid integer, university_fid integer, primary key (id)) engine=InnoDB;
alter table degree add constraint UK_by27bbt64p1ria17hy3khpyft unique (name);
alter table level add constraint UK_lrjnw0jty1fs19q56u0us8d0n unique (name);
alter table major add constraint UK_oi0ctjbjvktdcfxws9w2exiwb unique (name);
alter table university add constraint UK_ru212k5vib3yvu360fuy3h1g5 unique (name);
alter table user add constraint user_email_unique unique (email);
create table course_coursecrns (course_university_id integer not null, coursecrns_id integer not null, primary key (course_university_id, coursecrns_id)) engine=InnoDB;
create table course_instructor (courses_university_id integer not null, instructor_id integer not null, primary key (courses_university_id, instructor_id)) engine=InnoDB;
create table user_course (user_id integer not null, course_university_id integer not null, primary key (user_id, course_university_id)) engine=InnoDB;
create table user_interested_course (user_id integer not null, interested_course_university_id integer not null, primary key (user_id, interested_course_university_id)) engine=InnoDB;
alter table course_coursecrns add constraint UK_sg5l6bj5k4pbeule0v9hi7ahd unique (coursecrns_id);
alter table user_course add constraint UK_ojhtxuq944ptfxntlhrxvcshw unique (course_university_id);
alter table user_interested_course add constraint UK_7g14fn7qjihowhstipo6iy3vd unique (interested_course_university_id);
alter table course add constraint FKdgomx5qg5fvg9cgyh0sdh0vwo foreign key (degree_id) references degree (id);
alter table course add constraint FK4ag2rc4adjiesa1d0lcvnnq82 foreign key (university_id) references university (id);
alter table department add constraint FKh2ap9lv99txektaou64wpx8b2 foreign key (university_id) references university (id);
alter table level add constraint FKkvg8900rbtqtvud24vcsnw6rw foreign key (university_id) references university (id);
alter table review add constraint FKprox8elgnr8u5wrq1983degk foreign key (course_id) references course (university_id);
alter table review add constraint FKd3gy0ma4syq3tkgqyje0nbhb2 foreign key (instructor_id) references instructor (id);
alter table review add constraint FKn3q1vv5fmlyv3ouelg9ta0unb foreign key (university_id) references university (id);
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user (id);
alter table user add constraint FKnqnxmrttbx4tqiv2qkcv1ajcx foreign key (degree_fid) references degree (id);
alter table user add constraint FKfydmmlqn19qnpytrvob21vv4d foreign key (major_fid) references major (id);
alter table user add constraint FK2e0fnf9jmfw0jmwf9m0hihdst foreign key (university_fid) references university (id);
alter table course_coursecrns add constraint FK503m64orid5mj0ivll6oi9l99 foreign key (coursecrns_id) references coursecrn (id);
alter table course_coursecrns add constraint FKjnmg2hil9djxoyml1udh9w9f foreign key (course_university_id) references course (university_id);
alter table course_instructor add constraint FKltori8qni3ivrlovca4gd9yw3 foreign key (instructor_id) references instructor (id);
alter table course_instructor add constraint FK4yrginwid5ipfrsjcwbgddcmm foreign key (courses_university_id) references course (university_id);
alter table user_course add constraint FK4xq18kasyvpo8xmpnpfcr754m foreign key (course_university_id) references course (university_id);
alter table user_course add constraint FKpv8tt3252hb6kyej8p7e7pokl foreign key (user_id) references user (id);
alter table user_interested_course add constraint FKcjdnskifislkh57b59bfquop2 foreign key (interested_course_university_id) references course (university_id);
alter table user_interested_course add constraint FKtlxbvteqs80kpgnwhed1w0vir foreign key (user_id) references user (id);
